//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Assistant_System_v01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int Id_Certificates { get; set; }
        public string Name { get; set; }
        public System.DateTime Date_Certificates { get; set; }
        public int Id_Doctor { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
