//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Assistant_System_v01
{
    using System;
    using System.Collections.Generic;
    
    public partial class First_Aid
    {
        public int Id_First_Aid { get; set; }
        public string Explanation_First_Aid { get; set; }
        public int Id_Diseases { get; set; }
    
        public virtual Disease Disease { get; set; }
    }
}
