//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Assistant_System_v01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Medical_Assistant_System_Entities : DbContext
    {
        public Medical_Assistant_System_Entities()
            : base("name=Medical_Assistant_System_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergies { get; set; }
        public virtual DbSet<Appointment_Bocking> Appointment_Bocking { get; set; }
        public virtual DbSet<Available_Appointment> Available_Appointment { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<Diseases_Symptoms> Diseases_Symptoms { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Emergency> Emergencies { get; set; }
        public virtual DbSet<First_Aid> First_Aid { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<P_Personal_Infomation> P_Personal_Infomation { get; set; }
        public virtual DbSet<Patient_Account> Patient_Account { get; set; }
        public virtual DbSet<Patient_Allergy> Patient_Allergy { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Prescription_Diseases> Prescription_Diseases { get; set; }
        public virtual DbSet<Symptom> Symptoms { get; set; }
    }
}
