//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Assistant_System_v01
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Personal_Infomation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Personal_Infomation()
        {
            this.Emergencies = new HashSet<Emergency>();
            this.Patient_Allergy = new HashSet<Patient_Allergy>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int Id_Patient { get; set; }
        public string UserName { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string SocialStatus { get; set; }
        public Nullable<int> Length_p { get; set; }
        public Nullable<int> weight_p { get; set; }
        public string bloodType { get; set; }
        public int Id_Account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergency> Emergencies { get; set; }
        public virtual Patient_Account Patient_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Allergy> Patient_Allergy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
